# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout code
    - uses: actions/checkout@v4
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v4
      with:
      dotnet-version: '8.0.x'
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
      -name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
      app-name: 'NitinDemoTestRG' # Replace with your App Name
      slot-name: 'production' # Optional: if using deployment slots
      publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
      package: ${{env.DOTNET_ROOT}}/NitinDemoTestRG
