name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  AZURE_WEBAPP_NAME: current-time-service
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  publish:
    runs-on: window-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore
        run: dotnet restore ./NitinWebNewApp.sln
        
      - name: Build
        run: dotnet build ./NitinWebNewApp.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./NitinWebNewApp.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: GitHubTestDemo
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .